# Generated by Django 5.2.3 on 2025-06-20 11:58

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='EventCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
            ],
            options={
                'verbose_name': 'Categoria',
                'verbose_name_plural': 'Categorie',
            },
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Titolo')),
                ('slug', models.SlugField(max_length=200, unique=True)),
                ('description', models.TextField(verbose_name='Descrizione')),
                ('date', models.DateTimeField(verbose_name='Data e ora')),
                ('venue', models.CharField(max_length=200, verbose_name='Luogo')),
                ('address', models.TextField(verbose_name='Indirizzo')),
                ('city', models.CharField(max_length=100, verbose_name='Città')),
                ('image', models.ImageField(blank=True, null=True, upload_to='events/')),
                ('max_capacity', models.IntegerField(verbose_name='Capienza massima')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_active', models.BooleanField(default=True, verbose_name='Attivo')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='events', to='events.eventcategory')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventi',
                'ordering': ['date'],
            },
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome biglietto')),
                ('ticket_type', models.CharField(choices=[('standard', 'Standard'), ('vip', 'VIP'), ('premium', 'Premium'), ('student', 'Studente'), ('group', 'Gruppo')], default='standard', max_length=20)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Prezzo')),
                ('quantity', models.IntegerField(verbose_name='Quantità disponibile')),
                ('sold_quantity', models.IntegerField(default=0, verbose_name='Quantità venduta')),
                ('max_per_order', models.IntegerField(default=10, verbose_name='Max per ordine')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='events.event')),
            ],
            options={
                'verbose_name': 'Biglietto',
                'verbose_name_plural': 'Biglietti',
                'unique_together': {('event', 'name')},
            },
        ),
    ]
